# Generated by Django 3.2.7 on 2022-02-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_todo_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='my_cotribution',
            new_name='my_contribution',
        ),
    ]
