# Generated by Django 3.2.7 on 2022-02-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_my_cotribution_meeting_my_contribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
