# Generated by Django 3.2.7 on 2022-02-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
