# Generated by Django 3.2.7 on 2022-02-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_rename_author_quote_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
