# Generated by Django 3.2.7 on 2022-02-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_alter_diary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['date']},
        ),
    ]
