# Generated by Django 3.2.7 on 2022-02-24 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_alter_diary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['amount']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['start_time', 'title']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['deadline']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['open', 'deadline', 'updated']},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-date', 'source']},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-done', 'deadline', 'date_created']},
        ),
    ]
