# Generated by Django 3.2.7 on 2022-02-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_auto_20220224_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-date', '-date_created']},
        ),
        migrations.AddField(
            model_name='diary',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
