# Generated by Django 3.2.7 on 2022-02-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_auto_20220225_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-done', 'deadline', '-date_created']},
        ),
    ]
