# Generated by Django 3.2.7 on 2022-02-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_alter_todo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
