# Generated by Django 3.2.7 on 2022-02-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_alter_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
