# Generated by Django 3.2.7 on 2022-03-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0021_auto_20220225_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
