# Generated by Django 3.2.7 on 2022-02-18 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('author', models.CharField(max_length=200)),
                ('pages_total', models.IntegerField(max_length=10)),
                ('cover', models.TextField(blank=True, null=True)),
                ('format', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('reading_complete', models.BooleanField(default=False)),
                ('reading_ongoing', models.BooleanField(default=False)),
                ('reading_progress', models.IntegerField(default=0, max_length=3)),
                ('last_reading', models.DateTimeField(blank=True, null=True)),
                ('reading_closed', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
                ('rating', models.JSONField(blank=True, null=True)),
                ('average_rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book')),
            ],
        ),
    ]
