# Generated by Django 3.2.7 on 2022-02-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages_total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='reading_progress',
            field=models.IntegerField(default=0),
        ),
    ]
