# Generated by Django 3.2.7 on 2022-02-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_auto_20220218_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pages_total',
            new_name='pages',
        ),
    ]
