# Generated by Django 3.2.7 on 2022-02-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_rename_pages_total_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reading_progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
